name: Add JSON Key-Value to Index.html and Push
on:
  workflow_dispatch:
jobs:
  add_key_value:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: main
      

      - name: bb
        run: |
          pip install pyinstaller
          pyinstaller -F test.py
      - name: Commit and push changes
        run: |
          git config --local user.email "xumouren225588@163.com"
          git config --local user.name "xumouren225588"
          git add .
          git commit -m "Add key-value pair to JSON in Index.html"
          git push
