name: Read JSON and Output to Markdown

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Read JSON properties
      id: json_properties
      uses: ActionsTools/read-json-action@main
      with:
        file_path: 'test.json'

    - name: Generate Markdown list
      run: |
        # 假设JSON文件中有一个数组，每个元素都是一个对象，我们需要提取对象中的特定属性
        echo "## JSON Data List" > README.md
        jq -r '.[] | "\(.name) - \(.description)"' test.json >> README.md

    - name: Commit Markdown list
      run: |
        git config --local user.email "xumouren225588@163.com"
        git config --local user.name "xumouren225588"
        git add list.md
        git commit -m "Update JSON data list in Markdown" || echo "No changes to commit"
        git push
