name: Sync to Gitee on Push
on:
  push:
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Git
        run: |
          git config --global user.name "${{ secrets.GITEE_USERNAME }}"
          git config --global user.email "${{ secrets.GITEE_USERNAME }}@163.com"
      - name: Add Gitee remote
        run: |
          git remote add gitee https://${{ secrets.GITEE_USERNAME }}:${{ secrets.GITEE_TOKEN }}@gitee.com/${{ secrets.GITEE_USERNAME }}/xumouren225588.github.io.git
          # 将your-gitee-repo-name替换为你在Gitee上对应的仓库名称
      - name: Push to Gitee
        run: |
          git push gitee main # 如果你的主分支不是master，需要修改为对应的分支名称
